#!/bin/bash

CODE=${1}
LOG="${1}out"

if [ $# -lt 1 ]
then
	echo "usage: batchR <script.R> <script-args>"
	exit 1
fi

nohup R CMD BATCH --vanilla "--args ${2}" ${CODE} ${LOG} &
sleep 2
tail -f ${LOG}
 
